services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: coworking
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: [ "db_data:/var/lib/postgresql/data" ]
  app:
    build: .
    depends_on: [ db ]
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coworking
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      OAUTH_GOOGLE_ID: ${OAUTH_GOOGLE_ID}
      OAUTH_GOOGLE_SECRET: ${OAUTH_GOOGLE_SECRET}
    ports: ["8080:8080"]
volumes:
  db_data:
